# Generated by Django 5.2.3 on 2025-08-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedid',
            name='troco',
        ),
        migrations.AddField(
            model_name='pedidopagamento',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
