# Generated by Django 5.2.3 on 2025-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_remove_pedid_troco_pedidopagamento_troco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopagamento',
            name='resto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
